### ISSUE TITLE
Unable to install open-local on minicube

### ISSUE THREAD

**Issue by alex-arica** [alibaba/open-local#47] opened 2021-09-20 13:32 UTC
Hello,

I followed the installation guide [here](https://github.com/alibaba/open-local/blob/main/docs/user-guide.md)

When I typed ```kubectl get po -nkube-system  -l app=open-local``` the output was:
```
NAME                                              READY   STATUS      RESTARTS   AGE
open-local-agent-p2xdq                            3/3     Running     0          13m
open-local-csi-provisioner-59cd8644ff-n52xc       1/1     Running     0          13m
open-local-csi-resizer-554f54b5b4-xkw97           1/1     Running     0          13m
open-local-csi-snapshotter-64dff4b689-9g9wl       1/1     Running     0          13m
open-local-init-job--1-f9vzz                      0/1     Completed   0          13m
open-local-init-job--1-j7j8b                      0/1     Completed   0          13m
open-local-init-job--1-lmvqd                      0/1     Completed   0          13m
open-local-scheduler-extender-5dc8d8bb49-n44pn    1/1     Running     0          13m
open-local-snapshot-controller-846c8f6578-2bfhx   1/1     Running     0          13m
```

However, when I typed ``` kubectl get nodelocalstorage```, I got this output:

```
NAME       STATE   PHASE   AGENTUPDATEAT   SCHEDULERUPDATEAT   SCHEDULERUPDATESTATUS
minikube                                                       
```

According to the installation guide, the column ```The STATE``` should display ```DiskReady```.

And if I typed ```kubectl get nls -o yaml```, it outputted:

```
piVersion: v1
items:
- apiVersion: csi.aliyun.com/v1alpha1
  kind: NodeLocalStorage
  metadata:
    creationTimestamp: "2021-09-20T13:37:09Z"
    generation: 1
    name: minikube
    resourceVersion: "615"
    uid: 6f193362-e2b2-4053-a6e6-81de35c96eaf
  spec:
    listConfig:
      devices: {}
      mountPoints:
        include:
        - /mnt/open-local/disk-[0-9]+
      vgs:
        include:
        - open-local-pool-[0-9]+
    nodeName: minikube
    resourceToBeInited:
      vgs:
      - devices:
        - /dev/sdb
        name: open-local-pool-0
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

I am running Minicube on my desktop computer which has a SSD hard disk.

Thank you for your help.

**Comment by TheBeatles1994** [comment] 2021-09-20 23:59
Is ssd hard disk mounted?

Is ssd hard disk already formated? like ext4?

Run `minikube ssh` to log into the minikube environment, and type

- `lsblk`
- `blkid`

**Comment by alex-arica** [comment] 2021-09-21 07:50
Yes Minicube is installed on the SSD hard disk.

The command ```lsblk``` outputs:
```
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
nvme0n1     259:0    0 232.9G  0 disk 
|-nvme0n1p1 259:1    0   260M  0 part 
|-nvme0n1p2 259:2    0   128M  0 part 
|-nvme0n1p3 259:3    0   500M  0 part 
|-nvme0n1p4 259:4    0 114.9G  0 part 
|-nvme0n1p5 259:5    0 116.2G  0 part /tmp/hostpath-provisioner
`-nvme0n1p6 259:6    0   977M  0 part [SWAP]
```

The command ```blkid``` does not output anything.

**Comment by TheBeatles1994** [comment] 2021-09-21 09:03
```bash
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
nvme0n1     259:0    0 232.9G  0 disk 
|-nvme0n1p1 259:1    0   260M  0 part 
|-nvme0n1p2 259:2    0   128M  0 part 
|-nvme0n1p3 259:3    0   500M  0 part 
|-nvme0n1p4 259:4    0 114.9G  0 part 
|-nvme0n1p5 259:5    0 116.2G  0 part /tmp/hostpath-provisioner
`-nvme0n1p6 259:6    0   977M  0 part [SWAP]
```

Open-Local need a partition to create VG, you need to edit spec of nodelocalstorage.

```bash
...
    resourceToBeInited:
      vgs:
      - devices:
        - /dev/nvme0n1p4  # choose a partition that you wish to create VG with, not /dev/sdb
        name: open-local-pool-0
...
```

**Comment by alex-arica** [comment] 2021-09-21 09:06
Thank you. 

What you are suggesting is not in the installation guide [here](https://github.com/alibaba/open-local/blob/main/docs/user-guide.md)

Is there a reason for that?

**Comment by TheBeatles1994** [comment] 2021-09-21 09:46
User documentation is not detailed enough now, I will add more details later.

Try to output the log of open-local agent:

```
kubectl logs -nkube-system [open-local agent pod name] -c agent
```

**Comment by alex-arica** [comment] 2021-09-21 09:51
Thank you.

```
kubectl logs -nkube-system open-local-agent-xwlqt -c agent
time="2021-09-21T17:49:13+08:00" level=info msg="Version: v0.2.2, Commit: 314b005"
W0921 17:49:13.662051    4613 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2021-09-21T17:49:13+08:00" level=info msg="starting open-local agent"
time="2021-09-21T17:49:13+08:00" level=info msg="Started open-local agent"
time="2021-09-21T17:49:13+08:00" level=error msg="ListVolumeGroupNames error: nsenter: failed to execute vgs: No such file or directory"
time="2021-09-21T17:49:13+08:00" level=error msg="[getAllLocalSnapshotLV]List volume group names error: nsenter: failed to execute vgs: No such file or directory"
time="2021-09-21T17:49:13+08:00" level=error msg="[ExpandSnapshotLVIfNeeded]get open-local snapshot lv failed: nsenter: failed to execute vgs: No such file or directory"
time="2021-09-21T17:49:13+08:00" level=error msg="get node local storage minikube failed: nodelocalstorages.csi.aliyun.com \"minikube\" not found"
time="2021-09-21T17:49:13+08:00" level=info msg="creating node local storage minikube"
time="2021-09-21T17:49:43+08:00" level=error msg="ListVolumeGroupNames error: nsenter: failed to execute vgs: No such file or directory"
time="2021-09-21T17:49:43+08:00" level=error msg="[getAllLocalSnapshotLV]List volume group names error: nsenter: failed to execute vgs: No such file or directory"
time="2021-09-21T17:49:43+08:00" level=error msg="[ExpandSnapshotLVIfNeeded]get open-local snapshot lv failed: nsenter: failed to execute vgs: No such file or directory"
time="2021-09-21T17:49:43+08:00" level=error msg="LookupVolumeGroup error: nsenter: failed to execute vgs: No such file or directory"
time="2021-09-21T17:49:43+08:00" level=error msg="ListVolumeGroupNames error: nsenter: failed to execute vgs: No such file or directory"
time="2021-09-21T17:49:43+08:00" level=error msg="discover VG error: List volume group error: nsenter: failed to execute vgs: No such file or directory"
time="2021-09-21T17:50:13+08:00" level=error msg="ListVolumeGroupNames error: nsenter: failed to execute vgs: No such file or directory"
time="2021-09-21T17:50:13+08:00" level=error msg="[getAllLocalSnapshotLV]List volume group names error: nsenter: failed to execute vgs: No such file or directory"
time="2021-09-21T17:50:13+08:00" level=error msg="[ExpandSnapshotLVIfNeeded]get open-local snapshot lv failed: nsenter: failed to execute vgs: No such file or directory"
time="2021-09-21T17:50:13+08:00" level=error msg="LookupVolumeGroup error: nsenter: failed to execute vgs: No such file or directory"
time="2021-09-21T17:50:13+08:00" level=error msg="ListVolumeGroupNames error: nsenter: failed to execute vgs: No such file or directory"
time="2021-09-21T17:50:13+08:00" level=error msg="discover VG error: List volume group error: nsenter: failed to execute vgs: No such file or directory"
```

**Comment by TheBeatles1994** [comment] 2021-09-21 10:01
Do you install lvm2 in minikube vm?

**Comment by alex-arica** [comment] 2021-09-21 10:06
With Minikube ssh, I run:
```
sudo apt-get update
sudo apt-get install lvm2
```

And now when I run ```kubectl get nls```, the output is:
```
NAME       STATE       PHASE     AGENTUPDATEAT   SCHEDULERUPDATEAT   SCHEDULERUPDATESTATUS
minikube   DiskReady   Running   7s              7s                  

```

Thank you for your help. I am going to test it further, and this is a great progress thanks to you.

**Comment by TheBeatles1994** [comment] 2021-09-21 10:16
And thanks for your issue! I will add more details in user guide docs and provide more event to report errors.

**Comment by alex-arica** [comment] 2021-09-21 10:26
Thank you!

Once installed lvm2 and now if I check the logs of the open-local agent, the output is:
```
time="2021-09-21T18:19:42+08:00" level=warning msg="WARNING: ntfs signature detected on /dev/nvme0n1p4 at offset 3. Wipe it? [y/n]: [n]"
time="2021-09-21T18:19:42+08:00" level=error msg="CreatePhysicalVolume error: Aborted wiping of ntfs.\n1 existing signature left on the device."
time="2021-09-21T18:19:42+08:00" level=error msg="create physical volume /dev/nvme0n1p4 error: lvm: CreatePhysicalVolume: Aborted wiping of ntfs.\n1 existing signature left on the device."
time="2021-09-21T18:19:42+08:00" level=error msg="create vg open-local-pool-0 failed: lvm: CreatePhysicalVolume: Aborted wiping of ntfs.\n1 existing signature left on the device."
```

On my desktop computer I have also an ntfs partition. I think '/dev/nvme0n1p4' is ntfs.

How to now which partition to use?

```
docker@minikube:~$ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
nvme0n1     259:0    0 232.9G  0 disk 
|-nvme0n1p1 259:1    0   260M  0 part 
|-nvme0n1p2 259:2    0   128M  0 part 
|-nvme0n1p3 259:3    0   500M  0 part 
|-nvme0n1p4 259:4    0 114.9G  0 part 
|-nvme0n1p5 259:5    0 116.2G  0 part /tmp/hostpath-provisioner
`-nvme0n1p6 259:6    0   977M  0 part [SWAP]
```

I know that '/dev/nvme0n1p5' is ext4, as shown below:
```
docker@minikube:~$ df -Th
Filesystem     Type     Size  Used Avail Use% Mounted on
overlay        overlay  114G   46G   63G  43% /
tmpfs          tmpfs     64M     0   64M   0% /dev
shm            tmpfs     64M     0   64M   0% /dev/shm
/dev/nvme0n1p5 ext4     114G   46G   63G  43% /var
tmpfs          tmpfs     16G   11M   16G   1% /run
tmpfs          tmpfs     16G  8.0K   16G   1% /tmp
tmpfs          tmpfs    5.0M     0  5.0M   0% /run/lock
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/e106777d0feb887d7d7ffb76280c745cde0fc92e03b0edd79a364953e9365926/merged
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/81ada1503deb368ab36dabf0ab880bcef99776ac36fae6b19e66dd918f952c45/merged
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/bfaa44248537b5f3676ef421069973273cd0d8ee085e2519bca0fcc39757ffd9/merged
shm            tmpfs     64M     0   64M   0% /var/lib/docker/containers/faba99bbf4767aa11ce2e78ed2cd9f39f30df6b28fc2d2b4b2fd42f74b420307/mounts/shm
shm            tmpfs     64M     0   64M   0% /var/lib/docker/containers/11a302a11765a7ac91b7060d1d275c23ae4d6bdad36949fc4246dab8a249b06a/mounts/shm
shm            tmpfs     64M     0   64M   0% /var/lib/docker/containers/2a63fbd6fe60b051882e644d86e44f494acb743f4a42e5ff69b53cc5e1202f5b/mounts/shm
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/51c1be1dbde9d4e70017414ad70cf9112bf31fc3aa9765de57bbb9518149d334/merged
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/586ba6e4f9470fd596d5bd0d2747a51a3ea44033dd44f5ca9ef0b3e1e78a6b04/merged
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/17bb42f75da376e2e958aba1e8e38a0b9da9808937cc71c005f708603c7b727d/merged
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/2a54891a3e2f9837081c6a1b2f87bd9e9cc9c99d5d65571bb8501cda59a8908a/merged
shm            tmpfs     64M     0   64M   0% /var/lib/docker/containers/18e1d05231f4360d0287d734056d1240c79def9a2020f3291a832bd491a81799/mounts/shm
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/11f4e9c84a809f5ed37c39a5e423622fa7bae4918e7faa7a0666b1e9ab466a78/merged
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/2bef00e555d48af461ce98854e0629d73961cd5603687e1323c797c5e3bb2e58/merged
shm            tmpfs     64M     0   64M   0% /var/lib/docker/containers/c9f98cd8f12f552490f5b64fbc2577f1d2f3c7a88fe35499ceb3675f01c5ea03/mounts/shm
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/fc250826772ecdcdd92ef5e0979b8ae88ec377e2789b4f146ec261ece8a5a373/merged
shm            tmpfs     64M     0   64M   0% /var/lib/docker/containers/4c002537a195fce4224cd14338bbd456678b9fa99cf7ccc954153e34f940e0bb/mounts/shm
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/823f079cbaca9c6578bc2df431c2252188d745c27021407d73b14cbf257844e8/merged
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/fe0a152a8216e7737ed01c67e391be30e7d61077f52c059123d72e531de97b62/merged
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/852cd7bd58eda273048472f32ddedc820b2fd17921f49b75037eed33baeb3003/merged
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/2b567924ac2575ee37b0d01773069faad06c162341b3ba5493e981c19ded1247/merged
shm            tmpfs     64M     0   64M   0% /var/lib/docker/containers/08682f5b202e57e65d3769c5e579b4124baaada110efd30b559dd81c34d0edb6/mounts/shm
shm            tmpfs     64M     0   64M   0% /var/lib/docker/containers/ad39da698d6378dd02d6139a449d70d20a24b2b5fb906b4a9fc325b8af6a4776/mounts/shm
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/df64d7f50c8a4d35be7d316eed82cee4b9cc8d18ddafb2043b347844c98504e3/merged
shm            tmpfs     64M     0   64M   0% /var/lib/docker/containers/b45061ef01bec8426b3735e9c6f847b81add520d09c5c033f32f801d26c2c2a3/mounts/shm
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/ab51d7e2dda0ff5af7d34e213395aa1bf40e906c41716caedfee8672e5402600/merged
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/c5f4765cc23eee150e6c66e5b1486b14c52581eada7acbeed72695ba6dc9283f/merged
shm            tmpfs     64M     0   64M   0% /var/lib/docker/containers/92d6745f6c4cd304f7e18cecc8b272fcbdf786028417867a9cb9c61d4aac3340/mounts/shm
shm            tmpfs     64M     0   64M   0% /var/lib/docker/containers/56e97189ba00b7d1597663adb579ae7b23823ce1cf55561498dbaa9a593edc96/mounts/shm
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/0aa0bb89788d8cf8f2f7eb38a8aecdeb4c56c15014c08a8e859d7acdd0d29ad5/merged
shm            tmpfs     64M     0   64M   0% /var/lib/docker/containers/d172ff98bc0d8fc8610e8478ccf8fa88bb244139ce7624d12445233d145ff2fd/mounts/shm
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/3d02e3b01f82c86da2849d28b2c4d2282c15d63f87875dfb5a435314f1ccc523/merged
shm            tmpfs     64M     0   64M   0% /var/lib/docker/containers/f9382792c28561e4179a1304be2006bd80390c0f9f20ef6dff642f507b411eee/mounts/shm
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/f9229770eb50fc2741998a52d6661827cd7d8437841ca732afe0515637482cde/merged
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/be7a1fe21b8cba12c01bc5c09b46654bad21b2d7e8bc636e5d2ebaf8e4781f0f/merged
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/8ce39ca31624dd360381d060f740dffae8024c0cb88c7521fd4c139f94685ae8/merged
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/b1a4763ed1407bb53364dbada830ac72fb8faefb5d419446addeff410ff19701/merged
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/fd3190e97d90001dad8b78f5bfc7038e801455e2ef9a0727532161452ed5cbbc/merged
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/945ebf0c2e519b5037bd0fa8478b7c39b10d87b198f14c65d62443fc8b4d704e/merged
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/6a499fabcb6db392490c0458db8f140220cc4bf78c792dfc8054619d6268de79/merged
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/770b9b96c097e67333a5f0b3d0a05fd3deaee29c3222391d359abceb065a01a9/merged
overlay        overlay  114G   46G   63G  43% /var/lib/docker/overlay2/2fc30e882d12c89bd58f10e50c72cdfd7a0ebadd3d5b4cdab1aef343fa6a980f/merged
```

Should I use  '/dev/nvme0n1p5' when I edite nodelocalstorage, as follows?
```
resourceToBeInited:
    vgs:
    - devices:
      - /dev/nvme0n1p4
      name: open-local-pool-0
```

**Comment by alex-arica** [comment] 2021-09-21 10:26
Sorry I closed by mistake,

**Comment by TheBeatles1994** [comment] 2021-09-21 11:05
Your partition has a file system(ntfs).

Set env "Force_Create_VG" to “true” in container "agent" of open-local-agent deamonset

**Comment by alex-arica** [comment] 2021-09-21 11:36
You mentioned earlier that Open-Local needs a partition to create VG. 

The fact that the NTFS partition '/dev/nvme0n1p4'  has already data, will it be formatted?

If that's the case I may lose data used by my Windows partition.

**Comment by TheBeatles1994** [comment] 2021-09-21 12:18
Yes, the partition will be formatted and data will be lost.

So you need to use a partition which have no user data.

**Comment by alex-arica** [comment] 2021-09-21 12:25
Ok thank you.

**Comment by TheBeatles1994** [comment] 2021-09-21 12:29
Looking forward to your feedback!

**Comment by alex-arica** [comment] 2021-09-21 13:56
I created a new partition ```nvme0n1p7``` in my SSD hard drive, as follows:
```
docker@minikube:~$ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
nvme0n1     259:0    0 232.9G  0 disk 
|-nvme0n1p1 259:1    0   260M  0 part 
|-nvme0n1p2 259:2    0   128M  0 part 
|-nvme0n1p3 259:3    0   500M  0 part 
|-nvme0n1p4 259:4    0   113G  0 part 
|-nvme0n1p5 259:5    0 116.2G  0 part /tmp/hostpath-provisioner
|-nvme0n1p6 259:6    0   977M  0 part [SWAP]
`-nvme0n1p7 259:7    0   1.9G  0 part 

```
I modified the NLS by editing ```heml/templates/nlsc.yaml```, as follows:
```
    resourceToBeInited:
      vgs:
      - devices:
        - /dev/nvme0n1p7
        name: open-local-pool-0
```


I added a new env variable by editing ```heml/templates/agent.yaml```, as follows:
```
name: Force_Create_VG
value: "true"
```

I can create the pods successfully. The NLS outputs:
```
kubectl get nls 
NAME       STATE       PHASE     AGENTUPDATEAT   SCHEDULERUPDATEAT   SCHEDULERUPDATESTATUS
minikube   DiskReady   Running   1s              22m                 accepted

```


However, when I run ```kubectl apply -f ./example/lvm/sts-lvm.yaml```, the PV is not created. The PVC has the following events (see Warning):
```
kubectl describe pvc
Name:          html-nginx-lvm-0
Namespace:     default
StorageClass:  open-local-lvm
Status:        Pending
Volume:        
Labels:        app=nginx-lvm
Annotations:   volume.beta.kubernetes.io/storage-provisioner: local.csi.aliyun.com
               volume.kubernetes.io/selected-node: minikube
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Used By:       nginx-lvm-0
Events:
  Type     Reason                Age               From                                                                Message
  ----     ------                ----              ----                                                                -------
  Normal   WaitForFirstConsumer  37s               persistentvolume-controller                                         waiting for first consumer to be created before binding
  Normal   Provisioning          5s (x6 over 37s)  local.csi.aliyun.com_minikube_68d22d59-49f0-4b8f-97d9-842a2560fae5  External provisioner is provisioning volume for claim "default/html-nginx-lvm-0"
  Warning  ProvisioningFailed    5s (x6 over 37s)  local.csi.aliyun.com_minikube_68d22d59-49f0-4b8f-97d9-842a2560fae5  failed to provision volume with StorageClass "open-local-lvm": rpc error: code = Unknown desc = Create Lvm with error rpc error: code = Internal desc = failed to create lv: Failed to run cmd: /bin/nsenter --mount=/proc/1/ns/mnt --ipc=/proc/1/ns/ipc --net=/proc/1/ns/net --uts=/proc/1/ns/uts  lvcreate -n local-d7e9c7ce-ba73-4bd9-86a7-9fe833102de0 -L 1073741824b -W y -y open-local-pool-0, with out:   /dev/open-local-pool-0/local-d7e9c7ce-ba73-4bd9-86a7-9fe833102de0: not found: device not cleared
  Aborting. Failed to wipe start of new LV.
, with error: exit status 5
  Normal  ExternalProvisioning  1s (x4 over 37s)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "local.csi.aliyun.com" or manually created by system administrator
```

**Comment by TheBeatles1994** [comment] 2021-09-22 03:11
I found that this is a [known problem](https://listman.redhat.com/archives/linux-lvm/2015-June/msg00024.html): Debian is 'known' with it's own rewrite of lvm2 udev rules.
And those rules are not ack-ed by upstream and they are not correct.

Do you use the Debian system in your production environment? There is no problem in Centos.

**Comment by TheBeatles1994** [comment] 2021-09-22 03:43
I see that use `lvcreate -Zn....` can create logical volume successfully, but it is not recommended, because [trying to mount an unzeroed logical volume can cause the system to hang](https://linux.die.net/man/8/lvcreate).

**Comment by alex-arica** [comment] 2021-09-22 08:39
Thank you for highlighting the LVM issue with Debian.
I am using Debian in dev and production environments.  Unfortunately, it would be difficult for me to move to another distro at this stage.

**Comment by TheBeatles1994** [comment] 2021-09-22 09:35
So this is a LVM2 issue in Debian now.

If the command `lvcreate -n test-lv-in-debian -L 1G -W y -y open-local-pool-0` return success, that means you can use Open-Local.

**Comment by TheBeatles1994** [comment] 2021-09-23 09:36
If there are no other questions, I will close the issue

**Closed** 2021-09-23 09:36 UTC

**Comment by alex-arica** [comment] 2021-09-23 09:38
Thank you for your help so far. No more questions, but as it stands, it does not work locally for me. It is worth testing on Debian on your side.

**Comment by TheBeatles1994** [comment] 2021-09-23 09:44
What version of the Debian system are you using？ I try to reproduce it.

**Comment by alex-arica** [comment] 2021-09-23 09:45
Thank you. I am using Debian 11 Bullseye.

**Comment by TheBeatles1994** [comment] 2021-09-23 10:32
I can create logical volume successfully on my debian system.

**Kernel version(uname -a):** 
Linux *** 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux

**LVM version(lvm version):** 
    LVM version:     2.03.02(2) (2018-12-18)
    Library version: 1.02.155 (2018-12-18)
    Driver version:  4.39.0

**My commands are as following:**
- sudo apt-get update
- sudo apt-get install lvm2
- vgcreate open-local-pool-1 /dev/vdb # replace /dev/vdb to your partition
- lvcreate -n test-lv-in-debian -L 1G -W y -y open-local-pool-1

You can try to execute those command manually to see if there are still problems.

**Comment by alex-arica** [comment] 2021-09-23 10:37
Thank you. And does open-local work on your Debian?

**Comment by TheBeatles1994** [comment] 2021-09-23 13:55
Yes, I run a open-local container.

```bash
docker run --rm -it --entrypoint="" -v /sys:/sys -v /dev:/dev --privileged --pid=host thebeatles1994/open-local:v0.2.2 sh 

sh-4.2# nsenter --mount=/proc/1/ns/mnt --ipc=/proc/1/ns/ipc --net=/proc/1/ns/net --uts=/proc/1/ns/uts  lvcreate -n test-lv-in-debian-new -L 1G -W y -y open-local-pool-0
  Logical volume "test-lv-in-debian-new" created.
```

**Comment by alex-arica** [comment] 2021-09-23 14:00
Thank you.

As I mentioned in my message 2 days ago, with Minikube I couldn't get open-local to work when I followed the installation guide.

Have you tried the same approach with Minikube on Debia

If it worked for you, I will be interested in knowing what you did specifically that I haven't done.

**Comment by TheBeatles1994** [comment] 2021-09-23 15:42
Now I install Open-Local in minikube in my debian OS, and it worked when I create Pod using Open-Local PV.

I followed the installation guide too, and I edit spec of nls minikube(change /dev/sdb to /dev/vdb)

**Comment by alex-arica** [comment] 2021-09-23 15:44
Thank you for trying with Minikube and Debian.  I will try it again.

**Comment by TheBeatles1994** [comment] 2021-09-23 15:44
![image](https://user-images.githubusercontent.com/27069322/134539987-3d7197a4-2e49-469c-a50f-a3ce9f68d6ec.png)

**Comment by alex-arica** [comment] 2021-09-23 15:48
It works for me up to there as well.

However, when I run ```kubectl apply -f example/lvm/sts-lvm-snap.yaml``` the PV is not created.

**Comment by TheBeatles1994** [comment] 2021-09-23 15:52
![image](https://user-images.githubusercontent.com/27069322/134541244-131f3bf9-ca85-4a75-8075-fa2f3cec6416.png)

**Comment by TheBeatles1994** [comment] 2021-09-23 15:58
You must create original PV first by running `kubectl apply -f example/lvm/sts-lvm.yaml`
then create a volumesnapshot by running `kubectl apply -f example/lvm/snapshot.yaml`
and run `kubectl apply -f example/lvm/sts-lvm-snap.yaml` to create a Pod use new PV whose datasource is original PV.

**Comment by TheBeatles1994** [comment] 2021-09-23 16:05
When you want to expand PV, you must delete all snapshots of the PV. Or you will get this warning:

```bash
  Warning  VolumeResizeFailed     8s (x5 over 12s)   external-resizer local.csi.aliyun.com                                              resize volume "local-faa3ee32-0304-4906-92e9-7f642e87fca5" by resizer "local.csi.aliyun.com" failed: rpc error: code = Unknown desc = Create Lvm with error rpc error: code = Internal desc = failed to expand lv: Failed to run cmd: /bin/nsenter --mount=/proc/1/ns/mnt --ipc=/proc/1/ns/ipc --net=/proc/1/ns/net --uts=/proc/1/ns/uts  lvextend -L21474836480B open-local-pool-0/local-faa3ee32-0304-4906-92e9-7f642e87fca5, with out:   Snapshot origin volumes can be resized only while inactive: try lvchange -an.
```

**Comment by TheBeatles1994** [comment] 2021-09-23 16:06
> It works for me up to there as well.
> 
> However, when I run `kubectl apply -f example/lvm/sts-lvm-snap.yaml` the PV is not created.
> I will try again and hopefully it will work this time.

What do you do to make it work?

**Comment by alex-arica** [comment] 2021-09-23 16:12
I did not make it work yet. Because the PV does not create for some reasons. 
I will try again tomorrow and let you know (UK time).

**Comment by TheBeatles1994** [comment] 2021-09-23 16:24
I am jealous for you bro, cause Chinese programmer must work until after 9 p.m.(T⌓T)

**Comment by alex-arica** [comment] 2021-09-23 16:28
You guys work too hard!

Here in the UK we work between 9am and 5pm.

Thank you for your help so far. I appreciate it!

**Comment by TheBeatles1994** [comment] 2021-09-24 06:04
I https://github.com/alibaba/open-local/pull/48

**Comment by TheBeatles1994** [comment] 2021-09-24 23:24
Support reporting error events in nls when creating VG failed #49
